adapter:
  image: vmware/wavefront-adapter-for-istio
  tag: 0.1.0

credentials:
  direct:
    server: https://YOUR-INSTANCE.wavefront.com
    token: YOUR-API-TOKEN
  proxy:
    address: YOUR-PROXY-IP:YOUR-PROXY-PORT

metrics:
  flushInterval: 5s
  source: istio
  prefix: istio
  http: true
  tcp: true
